language: julia
os:
  - linux
  - osx
julia:
  - 1.2
  - 0.7
  - nightly

# Status will not show "failing" if nightly or v0.7 julia build fails.
matrix:
    fast_finish: true
    allow_failures:
        - julia: 0.7
        - julia: nightly
          
notifications:
    email: false

# Build documentation
jobs:
    include:
        - stage: Documentation
          julia: 1.2
          os: linux
          before_scipt:
          script:
              - julia --color=yes --project=docs -e
                'using Pkg; Pkg.add("Documenter");
                Pkg.develop(PackageSpec(path=pwd()));
                Pkg.instantiate();
                include("docs/make.jl")'
          after_success: skip
